days-before-stale: 60
days-before-close: 7
exempt-issue-labels:
  - pinned
  - security
  - backlog
exempt-pr-labels:
  - pinned
  - security
  - backlog
stale-issue-label: stale
stale-pr-label: stale
close-issue-message: >
  This issue was closed because it has been stale for some time.
close-pr-message: >
  This pull request was closed because it has been stale for some time.
