name: Mark stale issues and pull requests
on:
  schedule:
    - cron: '30 1 * * *'
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@3a9db7e6a41a89f618792c92c0e97cc736e1b13f
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/stale.yml
