name: Lint

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  fix-lint-issues:
    permissions:
      # To write linting fixes
      contents: write
      # To write Super-linter status checks
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Super-Linter
        uses: super-linter/super-linter@7bba2eeb89d01dc9bfd93c497477a57e72c83240 # x-release-please-version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DISABLE_ERRORS: true
          # Set your fix mode variables to true
          FIX_ANSIBLE: true
          FIX_BIOME_FORMAT: true
          FIX_BIOME_LINT: true
          FIX_CLANG_FORMAT: true
          FIX_CSHARP: true
          FIX_CSS_PRETTIER: true
          FIX_CSS: true
          FIX_DOTNET_SLN_FORMAT_ANALYZERS: true
          FIX_DOTNET_SLN_FORMAT_STYLE: true
          FIX_DOTNET_SLN_FORMAT_WHITESPACE: true
          FIX_ENV: true
          FIX_GITHUB_ACTIONS_ZIZMOR: true
          FIX_GO_MODULES: true
          FIX_GO: true
          FIX_GOOGLE_JAVA_FORMAT: true
          FIX_GRAPHQL_PRETTIER: true
          FIX_GROOVY: true
          FIX_HTML_PRETTIER: true
          FIX_JAVASCRIPT_ES: true
          FIX_JAVASCRIPT_PRETTIER: true
          FIX_JSON_PRETTIER: true
          FIX_JSON: true
          FIX_JSONC: true
          FIX_JSONC_PRETTIER: true
          FIX_JSX_PRETTIER: true
          FIX_JSX: true
          FIX_JUPYTER_NBQA_BLACK: true
          FIX_JUPYTER_NBQA_ISORT: true
          FIX_JUPYTER_NBQA_RUFF: true
          FIX_KOTLIN: true
          FIX_MARKDOWN_PRETTIER: true
          FIX_MARKDOWN: true
          FIX_NATURAL_LANGUAGE: true
          FIX_POWERSHELL: true
          FIX_PROTOBUF: true
          FIX_PYTHON_BLACK: true
          FIX_PYTHON_ISORT: true
          FIX_PYTHON_RUFF: true
          FIX_RUBY: true
          FIX_RUST_2015: true
          FIX_RUST_2018: true
          FIX_RUST_2021: true
          FIX_RUST_CLIPPY: true
          FIX_SCALAFMT: true
          FIX_SHELL_SHFMT: true
          FIX_SNAKEMAKE_SNAKEFMT: true
          FIX_SQLFLUFF: true
          FIX_TERRAFORM_FMT: true
          FIX_TSX: true
          FIX_TYPESCRIPT_ES: true
          FIX_TYPESCRIPT_PRETTIER: true
          FIX_VUE: true
          FIX_VUE_PRETTIER: true
          FIX_YAML_PRETTIER: true
          # To reuse the same Super-linter configuration that you use in the
          # lint job without duplicating it, see
          # https://github.com/super-linter/super-linter/blob/main/docs/run-linter-locally.md#share-environment-variables-between-environments
      - name: Commit and push linting fixes
        uses: stefanzweifel/git-auto-commit-action@28e16e81777b558cc906c8750092100bbb34c5e3
        with:
          branch: ${{ github.event.pull_request.head.ref || github.head_ref || github.ref }}
          commit_message: "chore: fix linting issues"
          commit_user_name: super-linter
          commit_user_email: super-linter@super-linter.dev
